version: '2'
services:
  db:
    restart: always
    image: postgres:latest
    volumes:
     - pgdata:/var/lib/postgresql/data/
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/var/app
    command: rails s -p 3000 -b '0.0.0.0'
    links:
      - db
volumes:
  pgdata:
